### ISSUE TITLE
Template with Array root does not render

### ISSUE THREAD

**Issue by mtitolo** [ideas/hapi-json-view#3]
Thanks for writing this! It's been great so far.

I'm having issues getting the root object of the response to be an array. I ultimately want to use a partial, but even a normal `json.set(..)` doesn't work.

**route:**

```
reply.view('users', { users: users }).code(200);
```

**users.js**

```
json.array(users, (json, user) => {
    json.set('name', user.name);
});
```

**Response:** 
`{}`

No errors are thrown.

**Comment by gergoerdosi** [comment]
Hi Michele,

There is a test case which creates an array in the root. Please take a look at it: https://github.com/ideas/hapi-json-view/blob/v1.0.0/test/runtime.js#L85-L93

The trick is to set the root `json` to an array:

``` javascript
json.set(json.array(['one', 'two'], (json, item) => {
  json.set(item);
}));
```

**Comment by mtitolo** [comment]
That API is terrible but I guess it does work.

**Comment by gergoerdosi** [comment]
Recommendations are welcome. If you have ideas to improve it, feel free to share it.

**Comment by mtitolo** [comment]
The extra `json.set` calls feel super weird. In an ideal world this would work:

```
json.array(users, (json, user) => {
    json.partial('user_partial', { user: user })
});
```

**Comment by mtitolo** [comment]
It'd also be nice to `set` multiples keys. Right now I have this:

```
json.set('name', user.name);
json.set('email', user.email);
json.set('id', user.id);
```

When this would be much nicer:

```
json.set({
    'name': user.name, 
    'email': user.email, 
    'id':user.id
});
```

**Comment by gergoerdosi** [comment]
Using `json.array` in the root makes sense, I will look into adding it. For the other issue you can use `json.extract`:

``` js
json.extract(user, ['name', 'email', 'id']);
```
